### ISSUE TITLE
configure retries per test

### ISSUE THREAD

**Issue by thumbnail** [AndreaCrotti/kaocha-retry#4]
Thanks for the plugin! Really helpful so far.

I'm wondering if it's possible to configure the retries on a per-test basis. Ideally i'd only retry known flaky tests, not everything. It'd also make it a bit more explicit which tests might be flaky.

Either marking the namespace / deftest as flaky would be fine
```clj
^:kaocha-retry.plugin/retry (ns my-flaky-test-ns ...)
;; or
^:kaocha-retry.plugin/retry (deftest my-flaky-test ...)
```

Metadata could also be used to override specific settings to (i.e. max-retries, timeout).

```clj
^{:kaocha-retry.plugin/retry {:max-retries 9}} (ns my-flaky-test-ns ...)
;; or
^{:kaocha-retry.plugin/max-retries 9} (ns my-flaky-test-ns ...)
```

Another possible solution would be an option in tests.edn;
```clj
:plugins [:kaocha-retry.plugin/retry
          ...]
:kaocha-retry.plugin/retry-ns ["my-flaky-test-ns"]
```

**Comment by AndreaCrotti** [comment]
My pleasure @thumbnail , that's a good idea actually, from these 3 options maybe the best one would be the option in tests.edn imho, at least to mark which tests should be retried.
Setting the max-retries per test I guess would be  more tricky though, but if setting some meta-data makes it then available in the kaocha testable map, then maybe it's also possible do that.

I think in any case these two things should be orthogonal, since you can leave the meta-data for the max-retries even if it does nothing, and you should be able to mark a flakey test without having to specify the number of retries.

**Comment by AndreaCrotti** [comment]
So I think what I've put together
https://github.com/AndreaCrotti/kaocha-retry/pull/6/files#diff-4b8b70acf7008e0279febfc8d96bfa9389b5f543c5343019715156a0e2da5be7R4
works specifying which namespaces you want to run already, allowing you to specify a list of regular expressions to match against (which could match the test name as well as the namespace actually).

Would that be fine?
I also added a sample option to configure the max retries per test
https://github.com/AndreaCrotti/kaocha-retry/pull/6/files#diff-4b8b70acf7008e0279febfc8d96bfa9389b5f543c5343019715156a0e2da5be7R5

which probably would be also easy to implement, would that kind of configuration be fine?

**Comment by thumbnail** [comment]
I had some time to test this today, and tested `ns-regex` which works exactly as expected 👍 Very nice.

The max retries per test aren't very important for me, so I use the global setting.

**Comment by AndreaCrotti** [comment]
Ok cool good to know, I'll merge and release the `ns-regex`, and I'll think about the max-retries a bit more.

**Comment by AndreaCrotti** [comment]
One thing that I'm not entirely sure about is if I should just limit to namespaces or allow to match the test name as well.
Atm it's actually matching on anything, so you could even match on specific tests inside a namespace.
If I leave it likes this I should maybe rename it to `test-regex`. If that's not very useful anyway I can make it a bit dumber and keep the name `ns-regex`.

**Comment by thumbnail** [comment]
It seems to make sense to match specific tests too, so maybe `test-regex` (or testable-regex) is a better name indeed. TBH I'd be fine with literal values instead of regexes too.

In my case, I have a couple of tests for sideeffects that can be flaky. I want to retry those exclusively, that way new tests aren't retried by default (and if they're flaky; it's more apparent)

**Comment by AndreaCrotti** [comment]
Yeah well, I think regexes make more sense since it's the same effort/complexity and is more powerful, if you just specify the test you want it will also just work.
Maybe it's a bit longer but I think `flakey-test-regex` is actually more clear, since `test-regex` is also kind of too vague.

The way we use this plugin is just to enable it on a specific test suite (so not all the tests), which are maybe just 5-6 files.
But yeah would be probably also for us to make even more explicit which files should be retried.

**Comment by thumbnail** [comment]
Naming things is almost always the most difficult thing :P `flakey-test-regex` implies the test should be flaky; but maybe it retries for different reasons. `retrying-test-regex` maybe?


> The way we use this plugin is just to enable it on a specific test suite

That's also an interesting way; I didn't realize this was possible

**Comment by AndreaCrotti** [comment]
Ah yes good point, and well to be clear @thumbnail 
we enable on a specific test suite by passing the extra `--plugin ..kaocha-retry` argument from the command line.
I don't think you can do the same thing from tests.edn unfortunately (but I should check again), and the disadvantage of course is that if you run the tests from the repl it would not use the retry plugin (but tbf in this case maybe it's not a big deal, you can retry yourself from the repl).

**Comment by AndreaCrotti** [comment]
I deployed version 0.4.0 in the end, using `:kaocha-retry.plugin/retrying-tests-regexes ["ns/test-*"]` in the end to configure it.
Let me know if you have any issues, thanks for the feedback.
